apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-simple-app
  labels:
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-simple-app
  template:
    metadata:
      labels:
        app: python-simple-app
    spec:
      containers:
      - name: python-simple-app
        image: sontran9xz/python-simple-app:latest
        ports:
        - containerPort: 8000
